apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubegreeter-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kubegreeter
  template:
    metadata:
      labels:
        app: kubegreeter
    spec:
      containers:
      - name: kubegreeter
        image: degemenc/kubegreeter
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: kubegreeter-service
spec:
  type: LoadBalancer
  selector:
    app: kubegreeter
  ports:
    - port: 8765
      targetPort: 8080
